/* 将离线求解产物 strategy_data.h 转换为浏览器可用的 public/strategies.js
 *
 * 用法：npm run gen （或 node tools/gen_strategies.js）
 * 只导出三个被使用的表（Q 值表有意不包含——完整最佳响应在运行时自算转移）：
 *   eq_policy_comp   [11][11][3]  电脑均衡策略
 *   eq_policy_player [11][11][3]  玩家均衡策略（Dirichlet 先验中心）
 *   V_values         [11][11]     均衡状态值（电脑视角；值迭代初值）
 * 索引约定：b1 为最外层（玩家子弹 0..10），b2 内层，动作序 [U, I, O]。
 */
'use strict';

const fs = require('fs');
const path = require('path');

const HEADER_PATH = path.join(__dirname, '..', '..', 'Game_XiBuNiuZai', 'strategy_data.h');
const OUT_PATH = path.join(__dirname, '..', 'public', 'strategies.js');

// 三个目标表的期望浮点数量
const EXPECT = { eq_policy_comp: 11 * 11 * 3, eq_policy_player: 11 * 11 * 3, V_values: 11 * 11 };
const V00_EXPECTED = 0.49483569; // V(0,0) 交叉验证基准（与日志无关的永久断言）

function extractAfterMarker(text, marker) {
  // 找到表名，再找 "= {"，然后括号配平找到对应结尾 "}"，返回其内部文本
  const namePos = text.indexOf(marker);
  if (namePos < 0) throw new Error('找不到表名: ' + marker);
  const eqPos = text.indexOf('=', namePos);
  const openPos = text.indexOf('{', eqPos);
  if (openPos < 0) throw new Error(marker + ' 缺少初始化器');
  let depth = 0;
  for (let i = openPos; i < text.length; i++) {
    const ch = text[i];
    if (ch === '{') depth++;
    else if (ch === '}') {
      depth--;
      if (depth === 0) return text.slice(openPos + 1, i);
    }
  }
  throw new Error(marker + ' 括号未闭合');
}

function extractFloats(inner) {
  return inner.match(/-?\d+\.\d+/g) || [];
}

function reshapeVerbatim(tokens, dims) {
  // 把扁平 token 列表重塑为嵌套数组；token 原样保留字符串以维持完整打印精度（含 -0.00000000）
  const [d0, d1, d2] = dims;
  const rows = [];
  let k = 0;
  for (let i = 0; i < d0; i++) {
    const r1 = [];
    for (let j = 0; j < d1; j++) {
      if (d2) {
        const r2 = [];
        for (let a = 0; a < d2; a++) r2.push(tokens[k++]);
        r1.push('[' + r2.join(', ') + ']');
      } else {
        r1.push(tokens[k++]);
      }
    }
    rows.push('[' + r1.join(', ') + ']');
  }
  if (k !== tokens.length) throw new Error('重塑后仍有剩余 token');
  return '[\n    ' + rows.join(',\n    ') + '\n  ]';
}

function main() {
  const text = fs.readFileSync(HEADER_PATH, 'utf8');
  const parts = {};

  for (const marker of Object.keys(EXPECT)) {
    const inner = extractAfterMarker(text, marker);
    const tokens = extractFloats(inner);
    if (tokens.length !== EXPECT[marker]) {
      throw new Error(
        marker + ' 期望 ' + EXPECT[marker] + ' 个浮点数，实际 ' + tokens.length +
        ' 个——strategy_data.h 格式可能已变化');
    }
    const dims = marker === 'V_values' ? [11, 11] : [11, 11, 3];
    parts[marker] = reshapeVerbatim(tokens, dims);
  }

  // V(0,0) 断言：取 V_values 第 0 行第 0 个数值（解析为数字比较）
  const v00 = Number(parts.V_values.match(/^\[\s*\[([^,\]]+)/)[1]);
  if (Math.abs(v00 - V00_EXPECTED) > 1e-12) {
    throw new Error('V(0,0) = ' + v00 + '，期望 ' + V00_EXPECTED + '——数据不一致');
  }

  const out =
    '/* AUTO-GENERATED by tools/gen_strategies.js from Game_XiBuNiuZai/strategy_data.h\n' +
    ' * 勿手改；重新生成：npm run gen\n' +
    ' * 索引约定：b1 为最外层（玩家子弹 0..10），b2 内层，动作序 [U, I, O]。\n' +
    ' * 终态单元格：eq 策略为全 0；V_values 为终局收益（0=玩家胜 / 1=电脑胜 / 0.5=双方10平局）。\n' +
    ' * Q 值表有意不包含（完整最佳响应在运行时自算转移）。\n' +
    ' */\n' +
    '(function (root, factory) {\n' +
    "  if (typeof module === 'object' && module.exports) module.exports = factory();\n" +
    '  else root.Strategies = factory();\n' +
    "})(typeof self !== 'undefined' ? self : this, function () {\n" +
    "  'use strict';\n\n" +
    '  var eq_policy_comp = ' + parts.eq_policy_comp + ';\n\n' +
    '  var eq_policy_player = ' + parts.eq_policy_player + ';\n\n' +
    '  var V_values = ' + parts.V_values + ';\n\n' +
    '  return {\n' +
    '    eq_policy_comp: eq_policy_comp,\n' +
    '    eq_policy_player: eq_policy_player,\n' +
    '    V_values: V_values\n' +
    '  };\n' +
    '});\n';

  fs.writeFileSync(OUT_PATH, out, 'utf8');
  console.log('OK: 已生成 ' + path.relative(process.cwd(), OUT_PATH));
  console.log('    eq_policy_comp 363 / eq_policy_player 363 / V_values 121 个数值');
  console.log('    V(0,0) = ' + v00.toFixed(8) + '（断言通过）');
}

main();
